#include <iostream>
#include <fstream>
#include "List.h"
#include <stdio.h>      /* printf, scanf, puts, NULL */
#include <stdlib.h>     /* srand, rand */
#include <time.h>       /* time */
#include "Sender.h"
#include "Receiver.h"
#include "Network.h"
#include <fstream>
using namespace std;




//git random comment
int main(){
	
	cout << "TCP Network Simulation by Chris Walter." << endl << endl;
	int nPkts;
	while (true){
		cout << "Please Enter the Number of Packets Here: ";
		cin >> nPkts;
		if (nPkts < 1 || nPkts >300){
			cout << "Please Enter a number between 1 and 300" << endl;
		}
		else{
			cout << "Preparing Network..." << endl;
			break;
		}
	}


	//file for outputing Network log
	ofstream fout("log.txt"); 
	
	fout << "*************************************************" << endl;
	fout << "Network Log Generated by Chris Walter" << endl;
	fout << "Pkt drop rate: 3% Corrupt: 2% Shuffle: 33% " << endl;
	fout << "After Each Round a Summer of Each List is Provided" << endl << endl;
	fout << "*************************************************" << endl;

	srand(1);

	//Creating Network Objects
	Sender sender;
	Receiver rec;
	Network network;

	//passing file output stream to each class
	network.setFout(&fout);
	sender.setFout(&fout);
	sender.inPkts.setFout(&fout);
	sender.outPkts.setFout(&fout);
	rec.setFout(&fout);
	rec.rAckBox.setFout(&fout);
	rec.rInbox.setFout(&fout);
	
	

	int roundCnt = 0;
	sender.setup(nPkts);
	rec.setup();

	while (sender.finished() == false){
		sender.process();
		rec.process();
		network.pick_up(sender);
		network.pick_up(rec);
		network.deliver(sender);
		network.deliver(rec);

		roundCnt++;
		fout <<endl<< "Round "<< roundCnt << " Summary " << "------------------------------------------->"<<endl;
		fout << "<--Sender Inbox: ";
		sender.inPkts.printList();
		fout << "<--Sender Outbox: ";
		sender.outPkts.printList();
		fout << "<--Receiver Inbox: ";
		rec.rInbox.printList();
		fout << "<--Receiver Outbox: ";
		rec.rAckBox.printList();
		fout << "End Round: " << roundCnt << "------------------------------------------->" << endl<<endl;
		
		
	}
	
	fout.close();
	cout << "Log.txt file has been created." << endl;

	system("pause");
	return 0;
}
